<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="fb_testTest" Id="{07648f02-c3bb-4b42-8587-c50362c01051}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_testTest EXTENDS fb_test IMPLEMENTS Testbench.IUnitTest]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Test_CheckCount" Id="{4cc048b3-3e23-43a4-8a8e-3d68cc51dd91}">
      <Declaration><![CDATA[METHOD Test_CheckCount
VAR_INPUT
  assertions : Testbench.IAssertions;
END_VAR
VAR CONSTANT
  amsNetId : Tc2_System.T_AmsNetID := '5.5.5.5.1.1';
  deviceId : UDINT := 9;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Count(1);
assertions.EqualsUint(1,SUPER^.o_ui_countValue,'Value not 1');
Count(2);
assertions.EqualsUint(5,SUPER^.o_ui_countValue,'Value not 5');]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="fb_testTest">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="fb_testTest.Test_CheckCount">
      <LineId Id="2" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="14" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>